from typing import runtime_checkable, Protocol, Optional, Any
from pathlib import Path
from typing_extensions import Self
from mcap_data_loader.callers.stack import DictBatch
from mcap_data_loader.basis.data_loader import Stage  # noqa: F401


@runtime_checkable
class ModelLike(Protocol):
    """Protocol for model-like objects."""

    def add_first_batch(self, batch: DictBatch) -> None: ...
    def train(self) -> None: ...
    def eval(self) -> None: ...
    def load(self, path: Optional[Path] = None) -> Self: ...
    def save(self, path: Path) -> None: ...
    def parameters(self) -> Any: ...
    def __call__(self, *args, **kwds) -> Any: ...
